version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install tox
      - npm install
  pre_build:
    commands:
      - tox -e pylint
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - tox
      - npm test

reports:
  reportGroupApiTests:
    files:
      - 'api_test_results.xml'
  reportGroupJSTests:
    files:
      - 'js_test_results.xml'

artifacts:
  files:
    - ./todo_app/static/dist/**.*
  discard-paths: yes
