version: 0.2

env:
  exported-variables:
    - APP_VERSION

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install tox
      - npm install
  pre_build:
    commands:
      - tox -e pylint
      - npm run lint
      - APP_VERSION=$(python versioning.py)
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - tox
      - npm test

reports:
  reportGroupApiTests:
    files:
      - 'api_test_results.xml'
  reportGroupJSTests:
    files:
      - 'js_test_results.xml'

artifacts:
  name: static
  files:
    - '**/*'
  base-directory: './todo_app/static/dist'
  secondary-artifacts:
    app_server:
      files:
        - '**/*'
      base-directory: '.'
