version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update -y
      - apt-get install -y xvfb
      - pip install tox
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - export USE_VIRTUAL_DISPLAY=TRUE
      - tox -e end_to_end

reports:
  reportGroupEndToEndTests:
    files:
      - 'end_to_end_test_results.xml'
